In [12]:
import torch

x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)


In [13]:
print(w)
print(b)

tensor([[-0.5066, -1.1029, -1.2258],
        [ 1.0495,  2.4205,  0.5860],
        [-0.5682, -0.0043, -1.2915],
        [ 0.3087,  0.4783, -0.5424],
        [ 1.8002, -1.5849, -0.0714]], requires_grad=True)
tensor([1.8239, 0.4696, 0.7508], requires_grad=True)


In [9]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x7fe1af505fc0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x7fe1af506b30>


In [14]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.3268, 0.2210, 0.0475],
        [0.3268, 0.2210, 0.0475],
        [0.3268, 0.2210, 0.0475],
        [0.3268, 0.2210, 0.0475],
        [0.3268, 0.2210, 0.0475]])
tensor([0.3268, 0.2210, 0.0475])


In [15]:
print(w)
print(b)

tensor([[-0.5066, -1.1029, -1.2258],
        [ 1.0495,  2.4205,  0.5860],
        [-0.5682, -0.0043, -1.2915],
        [ 0.3087,  0.4783, -0.5424],
        [ 1.8002, -1.5849, -0.0714]], requires_grad=True)
tensor([1.8239, 0.4696, 0.7508], requires_grad=True)


In [16]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


In [17]:
inp = torch.eye(4, 5, requires_grad=True)
out = (inp+1).pow(2).t()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])


In [76]:
inp.grad.zero_()
out = (inp+1).pow(2)
_ = torch.ones_like(out)
_[0,0] = 3
out.backward(_)
print(f"First call\n{inp.grad}")

First call
tensor([[12.,  2.,  2.,  2.,  2.],
        [ 2.,  4.,  2.,  2.,  2.],
        [ 2.,  2.,  4.,  2.,  2.],
        [ 2.,  2.,  2.,  4.,  2.]])


In [69]:
print(inp)
print(out)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]], requires_grad=True)
tensor([[4., 1., 1., 1., 1.],
        [1., 4., 1., 1., 1.],
        [1., 1., 4., 1., 1.],
        [1., 1., 1., 4., 1.]], grad_fn=<PowBackward0>)
